modLoader = "javafml" #mandatory
loaderVersion = "[36,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/RobertSkalko/Library-of-Exile-Rework"
[[mods]]
modId = "library_of_exile"
version = "1.4.8"
displayName = "Library Of Exile"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile = "icon.png" #
credits = ""
authors = "Love, Cheese and small house plants"
description = '''
Library mod for Mine and Slash and mine and slash accessories.
'''
[[dependencies.library_of_exile]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.library_of_exile]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
